---
advertised:
  type: boolean
  label: Advertised
  description: The layer is advertised through the web UI and API.
published:
  type: boolean
  label: Published
  description: The layer is published ("can be viewed by anonymous users" or "the public").
view_geodashdashboard:
  type: stringarray
  label: Can View
  placeholder: Can View
  required: true
  description: "The users who can view the dashboard."
  source: users
change_geodashdashboard:
  type: stringarray
  label: Can Edit
  placeholder: Can Edit
  required: true
  description: "The users who can edit the dashboard."
  source: users
delete_geodashdashboard:
  type: stringarray
  label: Can Delete
  placeholder: Can Delete
  required: true
  description: "The users who can delete the dashboard."
  source: users
